export default defineAppConfig({
  ui: {
    primary: 'merah',
    gray: 'slate',
    container: {
      base: 'mx-auto',
      padding: 'px-4 sm:px-16 lg:px-16',
      constrained: 'max-w-7xl',
    },
    card: {
      base: 'overflow-hidden',
      background: 'bg-white dark:bg-gray-900',
      divide: 'divide-y divide-gray-200 dark:divide-gray-800',
      ring: 'ring-1 ring-gray-200 dark:ring-gray-800',
      rounded: 'rounded-lg',
      shadow: 'shadow',
      body: {
        base: '',
        background: '',
        padding: 'p-3  sm:p-4',
      },
      header: {
        base: '',
        background: '',
        padding: 'px-4 py-5 sm:px-6',
      },
      footer: {
        base: '',
        background: '',
        padding: 'px-4 py-4 sm:px-6',
      },
    },

    tabs: {
      wrapper: 'relative space-y-2',
      container: 'relative w-full',
      base: 'focus:outline-none',
      list: {
        base: 'relative ',
        background: 'bg-gray-100 dark:bg-gray-900',
        rounded: 'rounded-md',
        shadow: 'md',
        padding: 'p-1',
        height: 'h-10',
        width: 'w-full',
        marker: {
          wrapper: 'absolute top-[4px] left-[4px] duration-200 ease-out focus:outline-none',
          base: 'w-full h-full',
          background: 'bg-merah dark:bg-merah',
          rounded: 'rounded-md',
          shadow: 'shadow-sm',
        },
        tab: {
          base: 'relative inline-flex items-center justify-center flex-shrink-0 w-full ui-focus-visible:outline-0 ui-focus-visible:ring-2 ui-focus-visible:ring-primary-500 dark:ui-focus-visible:ring-primary-400 ui-not-focus-visible:outline-none focus:outline-none disabled:cursor-not-allowed disabled:opacity-75 transition-colors duration-200 ease-out',
          background: '',
          active: 'text-gray-900 dark:text-white',
          inactive: 'text-gray-500 dark:text-gray-400',
          height: 'h-8',
          padding: 'px-3',
          size: 'text-sm',
          font: 'font-medium',
          rounded: 'rounded-md',
          shadow: '',
        },
      },
    },
    popover: {
      wrapper: 'relative ',
      container: 'z-50 group',
      trigger: 'inline-flex w-full',
      width: '',
      background: 'bg-white dark:bg-gray-900',
      shadow: 'shadow-lg',
      rounded: 'rounded-md',
      ring: 'ring-1 ring-gray-200 dark:ring-gray-800',
      base: 'overflow-hidden focus:outline-none relative',
      transition: {
        enterActiveClass: 'transition ease-out duration-200',
        enterFromClass: 'opacity-0 translate-y-1',
        enterToClass: 'opacity-100 translate-y-0',
        leaveActiveClass: 'transition ease-in duration-150',
        leaveFromClass: 'opacity-100 translate-y-0',
        leaveToClass: 'opacity-0 translate-y-1',
      },
      overlay: {
        base: 'fixed inset-0 transition-opacity z-50',
        background: 'bg-gray-200/75 dark:bg-gray-800/75',
        transition: {
          enterActiveClass: 'ease-out duration-200',
          enterFromClass: 'opacity-0',
          enterToClass: 'opacity-100',
          leaveActiveClass: 'ease-in duration-150',
          leaveFromClass: 'opacity-100',
          leaveToClass: 'opacity-0',
        },
      },
      popper: {
        strategy: 'fixed',
      },
      arrow: {
        base: 'invisible before:visible before:block before:rotate-45 before:z-[-1] before:w-2 before:h-2',
        ring: 'before:ring-1 before:ring-gray-200 dark:before:ring-gray-800',
        rounded: 'before:rounded-sm',
        background: 'before:bg-gray-200 dark:before:bg-gray-800',
        shadow: 'before:shadow',
        placement: 'group-data-[popper-placement*=\'right\']:-left-1 group-data-[popper-placement*=\'left\']:-right-1 group-data-[popper-placement*=\'top\']:-bottom-1 group-data-[popper-placement*=\'bottom\']:-top-1',
      },
    },

  },
})
